SELECT [Id]
        ,[CustomerId]
        ,[CustomerName]
        ,[CustomerAlias]
        ,[CustomerAddress]
        ,[ProductId]
        ,[ProductBrand]
        ,[ProductName]
        ,[ProductPackaging]
        ,[ProductPcsInCtn]
        ,[BatchNumber]
        ,[ExpiredDate]
        ,[InvoiceNo]
        ,[InvoiceDate]
        ,[InvoiceQty]
        ,[InvoiceUnit]
        ,[UnitPrice]
        ,[GrossValue]
        ,[DiscountValue]
        ,[DiscountPct]
        ,[NetValue]
        ,[InKg]
        ,[GeisaPOId]
        ,[ShipDate]
        ,[SalesmanNameGMK]
        ,[CompanyId]
        ,[CreatedDate]
FROM [GiselXDb].[dbo].[SalesTransaction]