SELECT [Id]
      ,[ProductId]
      ,[ProductName]
      ,[ProductPackaging]
      ,[ProductPcsInCtn]
      ,[ProductNetto]
      ,[ProductUnit]
      ,[SaldoAwal]
      ,[SaldoMasukPO]
      ,[SaldoAkhir]
      ,[BatchNumber]
      ,[ExpiredDate]
      ,[CompanyId]
      ,[CreatedDate]
  FROM [GiselXDb].[dbo].[Stock]