<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GiselX.Repository.Interface\GiselX.Repository.Interface.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="Dapper.SqlBuilder" Version="2.1.66" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    </ItemGroup>

</Project>
